### ISSUE TITLE
Misc code improvements

### ISSUE THREAD

**Issue by kmdeck** [bischtob/Downscaling.jl#101]
- [x] power spectrum code: The power spectrum code from ClimateMachine has a mysterious factor of 2*pi*k^2/dx^2 in front. It's unclear what this is for. Akshay is looking into it, we can ask Lenka too. but, if we dont have it, we have something that is proportional to the PSD - i.e. flat for white noise. this is a more natural way of presenting it, I think, and cleaner (k -> wavenumber, not wavenumber *2*pi/L). If we update this, we need to update t_cutoff, spectrum plots, etc. We should do it, though.

- [x] compute and report uncertainty on qq plots (quantify deviation from 1:1 line) #109 
- [x] report mean and std of distribution of means, and their uncertainties. #109 
- [x] Use epsilon consistently (or dont) #111
